Repository hmcts/bulk-scan-processor, pull requests merged in 2020-12, with the labels that each got.

#1621 fix null & empty list handling in reconciliation detail report
  src/main/java/uk/gov/hmcts/reform/bulkscanprocessor/services/reports/ReconciliationService.java
  src/test/java/uk/gov/hmcts/reform/bulkscanprocessor/services/reports/ReconciliationServiceTest.java
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-1621

#1627 Set the comonent var for DBs with override name for staging
  config/owasp/suppressions.xml
  infrastructure/main.tf
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-1627

#1628 avoid from vulnerability
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-1628

#1632 fix tomcat vulnerability
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-1632

#1633 syncBranchesWithMaster
  Jenkinsfile_CNP
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-1633

#1636 bump shedlock libs
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-1636

#1637 remove proxy
  Jenkinsfile_CNP
  src/functionalTest/java/uk/gov/hmcts/reform/bulkscanprocessor/config/TestConfiguration.java
  src/functionalTest/java/uk/gov/hmcts/reform/bulkscanprocessor/controllers/BaseFunctionalTest.java
  src/functionalTest/resources/application.conf
  src/main/java/uk/gov/hmcts/reform/bulkscanprocessor/config/HttpConfiguration.java
  src/main/java/uk/gov/hmcts/reform/bulkscanprocessor/config/StorageConfiguration.java
  src/main/resources/application.yaml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-1637
