Repository hmcts/bulk-scan-processor, pull requests merged in 2021-12, with the labels that each got.

#2166 DTSBPS-119 add file upload size limit
  build.gradle
  src/main/java/uk/gov/hmcts/reform/bulkscanprocessor/exceptions/FileSizeExceedMaxUploadLimit.java
  src/main/java/uk/gov/hmcts/reform/bulkscanprocessor/model/common/Event.java
  src/main/java/uk/gov/hmcts/reform/bulkscanprocessor/services/UploadEnvelopeDocumentsService.java
  src/main/java/uk/gov/hmcts/reform/bulkscanprocessor/tasks/processor/ZipFileProcessor.java
  src/test/java/uk/gov/hmcts/reform/bulkscanprocessor/services/UploadEnvelopeDocumentsServiceTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscanprocessor/tasks/processor/ZipFileProcessorTest.java
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2166

#2174 Bump log4j version
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2174

#2183 Updated fortify release id
  config/fortify-client.properties
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2183
