Repository hmcts/bulk-scan-processor, pull requests merged in 2021-08, with the labels that each got.

#2030 DTSBPS-687: fortify integration on nightly build
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2030

#2032 DTSBPS-708 use-git-native-dependabot
  .dependabot/config.yml
  .github/dependabot.yml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2032

#2040 DTSBPS-712 owasp arrangements
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2040

#2043 Code smells
  src/main/java/uk/gov/hmcts/reform/bulkscanprocessor/controllers/ZipStatusController.java
  src/main/java/uk/gov/hmcts/reform/bulkscanprocessor/exceptions/EnvelopeRejectionException.java
  src/main/java/uk/gov/hmcts/reform/bulkscanprocessor/exceptions/EnvelopeStateException.java
  src/main/java/uk/gov/hmcts/reform/bulkscanprocessor/exceptions/InvalidEnvelopeException.java
  src/main/java/uk/gov/hmcts/reform/bulkscanprocessor/model/mapper/EnvelopeMapper.java
  src/main/java/uk/gov/hmcts/reform/bulkscanprocessor/services/EnvelopeAccessService.java
  src/main/java/uk/gov/hmcts/reform/bulkscanprocessor/services/reports/ReconciliationService.java
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2043

#2024 SSCS test PO box
  src/main/resources/application.yaml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2024

#2052 DTSBPS-716 fix terraform
  infrastructure/state.tf
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2052

#2048 Code smells
  src/test/java/uk/gov/hmcts/reform/bulkscanprocessor/tasks/monitoring/IncompleteEnvelopesTaskTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscanprocessor/tasks/monitoring/NoNewEnvelopesTaskTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscanprocessor/tasks/processor/BlobManagerTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscanprocessor/util/CsvWriterTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscanprocessor/util/FailingInstantDeserialiserTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscanprocessor/util/FlywayNoOpStrategyTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscanprocessor/util/InstantDeserializerTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscanprocessor/util/OcrDataDeserializerTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscanprocessor/validation/EnvelopeProcessorValidationTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscanprocessor/validation/MetafileJsonValidatorTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscanprocessor/validation/MetafileJsonValidatorTestForInvalidFiles.java
  src/test/java/uk/gov/hmcts/reform/bulkscanprocessor/validation/OcrPresenceValidatorTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscanprocessor/validation/OcrValidatorTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscanprocessor/validation/envelope/DocumentTypesValidationTest.java
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2048

#2053 Code smells
  src/test/java/uk/gov/hmcts/reform/bulkscanprocessor/validation/EnvelopeValidatorTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscanprocessor/validation/OcrPresenceValidatorTest.java
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2053
