Repository hmcts/bulk-scan-processor, pull requests merged in 2022-11, with the labels that each got.

#2702 Suppress spring-security and tomcat-embed vulnerabilities (DTSBPS-1143)
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2702

#2704 Add distribution to Github actions (DTSBPS-1147)
  .github/workflows/ci.yml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2704

#2738 DTSBPS-1163: Suppress CVE-2016-1000027
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2738

#2749 Migrate blobstorage chart from osba to ASO
  Jenkinsfile_CNP
  charts/bulk-scan-processor/Chart.yaml
  charts/bulk-scan-processor/values.preview.template.yaml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2749

#2765 Revert "Bump info.solidsoft.pitest from 1.7.0 to 1.9.11"
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2765
