Repository hmcts/bulk-scan-processor, pull requests merged in 2022-07, with the labels that each got.

#2476 Suppress CVE-2022-31569
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2476

#2477 Bump java chart version
  charts/bulk-scan-processor/Chart.yaml
  charts/bulk-scan-processor/values.preview.template.yaml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2477

#2482 DTSBPS-1020: Pinned azureem version
  infrastructure/state.tf
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2482
