Repository hmcts/bulk-scan-processor, pull requests merged in 2022-05, with the labels that each got.

#2355 DTSBPS-933: Added ABORTED status
  src/main/java/uk/gov/hmcts/reform/bulkscanprocessor/entity/Status.java
  src/main/java/uk/gov/hmcts/reform/bulkscanprocessor/services/EnvelopeActionService.java
  src/test/java/uk/gov/hmcts/reform/bulkscanprocessor/services/EnvelopeActionServiceTest.java
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2355

#2359 Decommission bulk scan processor old db (DTSBPS-929)
  infrastructure/main.tf
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2359

#2360 DTSBPS-933: Aborted controller
  src/integrationTest/java/uk/gov/hmcts/reform/bulkscanprocessor/controllers/ActionControllerTest.java
  src/main/java/uk/gov/hmcts/reform/bulkscanprocessor/controllers/ActionController.java
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2360

#2367 Resolve CVE-2022-24823 (DTSBPS-943)
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2367

#2368 Suppress CVE-2016-1000027
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2368

#2369 Suppress CVE-2022-29885 (DTSBPS-947)
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2369

#2375 DTSBPS-948 : Update scanning_date format to include milliseconds
  src/integrationTest/java/uk/gov/hmcts/reform/bulkscanprocessor/features/OcrDataSerializationJourneyTest.java
  src/main/java/uk/gov/hmcts/reform/bulkscanprocessor/model/out/msg/Document.java
  src/test/java/uk/gov/hmcts/reform/bulkscanprocessor/model/out/msg/DocumentTest.java
  src/test/resources/metafiles/valid/envelope-with-ocr-data.json
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2375
