Repository hmcts/bulk-scan-processor, pull requests merged in 2022-04, with the labels that each got.

#2318 Suppressed vulnerability
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2318

#2329 Suppress Spring vulnerability
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2329

#2330 DTSBPS-916: Upgrade spring boot version
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2330

#2310 Use Bulkscan postgres v11 database
  charts/bulk-scan-processor/Chart.yaml
  charts/bulk-scan-processor/values.yaml
  infrastructure/main.tf
Labels: do not merge, ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2310
