Repository hmcts/bulk-scan-processor, pull requests merged in 2022-03, with the labels that each got.

#2270 Privatelaw config
  charts/bulk-scan-processor/Chart.yaml
  charts/bulk-scan-processor/values.yaml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2270

#2275 bump java chart
  charts/bulk-scan-processor/Chart.yaml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2275

#2281 Update azuead version instead of #2277
  infrastructure/state.tf
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2281

#2276 Create Bulkscan processor database with postgres version 11 (DTSBPS-770)
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2276

#2292 [DO NOT MERGE] Use premium servicebus (DTSBPS-886)
  charts/bulk-scan-processor/Chart.yaml
  charts/bulk-scan-processor/values.yaml
Labels: do not merge, ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2292

#2286 DTSBPS-890 bump azure-storage-blob
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/reform/bulkscanprocessor/controllers/GetSasTokenTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/bulkscanprocessor/controllers/SasTokenControllerTest.java
  src/integrationTest/resources/docker-compose.yml
  src/test/java/uk/gov/hmcts/reform/bulkscanprocessor/services/SasTokenGeneratorServiceTest.java
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2286

#2297 Delete incorrect postgres v11 host secret
  infrastructure/main.tf
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2297

#2298 Add postgres v11 host secret
  infrastructure/main.tf
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2298

#2301 DTSBPS-891 copy premium value from reform-scan vault to bulk-scan
  README.md
  infrastructure/main.tf
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2301

#2296 DTSBPS-891 use premium service bus
  charts/bulk-scan-processor/Chart.yaml
  charts/bulk-scan-processor/values.aat.template.yaml
  charts/bulk-scan-processor/values.yaml
Labels: do not merge, ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2296

#2303 suppress vulnerability
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2303

#2304 use staging notification queue
  charts/bulk-scan-processor/values.aat.template.yaml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2304

#2308 avoid jackson databind vulnerability
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2308
