Repository hmcts/bulk-scan-processor, pull requests merged in 2023-11, with the labels that each got.

#3188 master branch fixes
  Jenkinsfile_CNP
  build.gradle
  charts/bulk-scan-processor/Chart.yaml
  charts/bulk-scan-processor/values.preview.template.yaml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-3188

#3191 FACT-1514 Postgres flexible servers
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/preview.tfvars
  infrastructure/prod.tfvars
  infrastructure/provider.tf
  infrastructure/state.tf
  infrastructure/stg.tfvars
  infrastructure/test_config.tf
  infrastructure/tf-db-flexible-secrets.tf
  infrastructure/tf-db-flexible.tf
  infrastructure/variables.tf
Labels: ns:bsp, prd:bulk-scan, add-or-update, rel:bulk-scan-processor-pr-3191

#3195 fixing
  Jenkinsfile_CNP
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-3195

#3197 FACT-1530 change aat to use correct servicebus
  charts/bulk-scan-processor/values.aat.template.yaml
Labels: ns:bsp, prd:bulk-scan, destroy, rel:bulk-scan-processor-pr-3197

#3198 reentering namespace value
  Jenkinsfile_CNP
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-3198
