Repository hmcts/bulk-scan-processor, pull requests merged in 2023-02, with the labels that each got.

#2905 DTSBPS-1274: Upgrade to Java 17
  Dockerfile
  build.gradle
  charts/bulk-scan-processor/values.yaml
  config/checkstyle/checkstyle.xml
  lib/AI-Agent.xml
  lib/applicationinsights.json
  src/integrationTest/java/uk/gov/hmcts/reform/bulkscanprocessor/controllers/ProcessEventControllerTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/bulkscanprocessor/controllers/ReportsControllerTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/bulkscanprocessor/tasks/BlobProcessorTaskTestForMultiplePoBoxes.java
  src/main/java/uk/gov/hmcts/reform/bulkscanprocessor/entity/Status.java
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2905

#2919 DTSBPS-1293: Suppress CVE-2022-31690, CVE-2022-31692
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2919

#2921 DTSBPS-1290: Bump chart version
  charts/bulk-scan-processor/Chart.yaml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2921

#2929 DTSBPS-1294: Removed unused variable ilbIp
  infrastructure/variables.tf
Labels: ns:bsp, prd:bulk-scan, no-changes, rel:bulk-scan-processor-pr-2929

#2958 DTSPBS-1308-mutation test changes
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2958

#2976 DTSBPS-1318: Suppress CVE-2022-45688
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2976
