Repository hmcts/bulk-scan-processor, pull requests merged in 2023-01, with the labels that each got.

#2835 DTSBPS-1210: Update envelope classification and status in the repository
  src/integrationTest/java/uk/gov/hmcts/reform/bulkscanprocessor/entity/EnvelopeRepositoryTest.java
  src/main/java/uk/gov/hmcts/reform/bulkscanprocessor/entity/EnvelopeRepository.java
  src/test/java/uk/gov/hmcts/reform/bulkscanprocessor/helper/EnvelopeCreator.java
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2835

#2836 DTSBPS-1210: Update actions service to update envelope classification and reprocess
  src/main/java/uk/gov/hmcts/reform/bulkscanprocessor/exceptions/EnvelopeClassificationException.java
  src/main/java/uk/gov/hmcts/reform/bulkscanprocessor/services/EnvelopeActionService.java
  src/test/java/uk/gov/hmcts/reform/bulkscanprocessor/services/EnvelopeActionServiceTest.java
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2836

#2841 DTSBPS-1210 - Add endpoint to update envelope classification
  src/integrationTest/java/uk/gov/hmcts/reform/bulkscanprocessor/controllers/ActionControllerTest.java
  src/main/java/uk/gov/hmcts/reform/bulkscanprocessor/controllers/ActionController.java
  src/main/java/uk/gov/hmcts/reform/bulkscanprocessor/exceptionhandlers/ResponseExceptionHandler.java
  src/main/java/uk/gov/hmcts/reform/bulkscanprocessor/services/EnvelopeActionService.java
  src/test/java/uk/gov/hmcts/reform/bulkscanprocessor/services/EnvelopeActionServiceTest.java
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2841

#2847 DTSBPS-1235: Suppressed CVE-2021-4277
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2847

#2853 DTSBPS-1236: Suppressed dependencies
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2853

#2873 Use standard dockerfile format
  Dockerfile
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2873

#2896 DTSBPS-1258: Upgraded AppInsight
  Dockerfile
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2896

#2897 DTSBPS-1276: cleanup suppressions
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-2897
