Repository hmcts/bulk-scan-processor, pull requests merged in 2024-08, with the labels that each got.

#3314 FACT-1836 Private Law Onboarding Phase 2: Update Payment Enabled property
  charts/bulk-scan-processor/Chart.yaml
  charts/bulk-scan-processor/values.yaml
  src/main/resources/application-dev.yaml
  src/main/resources/application.yaml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-3314

#3315 FACT-1906 updated dependancies
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-3315

#3324 Remove db image in compose
  docker-compose.yml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-3324
