Repository hmcts/bulk-scan-processor, pull requests merged in 2025-01, with the labels that each got.

#3370 FACT-2069 changed to 15 to match prod
  charts/bulk-scan-processor/values.aat.template.yaml
  charts/bulk-scan-processor/values.preview.template.yaml
  docker/database/Dockerfile
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-3370

#3371 FACT-1952 - adds config for onboarding sscs-ibca
  src/main/resources/application-dev.yaml
  src/main/resources/application.yaml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-3371

#3372 Update application.yaml
  src/main/resources/application.yaml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-processor-pr-3372
